items:
- uid: EvilDICOM.Anonymization.Settings
  id: EvilDICOM.Anonymization.Settings
  children:
  - EvilDICOM.Anonymization.Settings.AnonymizationSettings
  - EvilDICOM.Anonymization.Settings.DateSettings
  langs:
  - csharp
  - vb
  name: EvilDICOM.Anonymization.Settings
  fullName: EvilDICOM.Anonymization.Settings
  type: Namespace
  source:
    remote:
      path: EvilDICOM/EvilDICOM/Anonymization/Settings/DateSettings.cs
      branch: master
      repo: https://github.com/rexcardan/Evil-DICOM.git
    path: EvilDICOM/EvilDICOM/Anonymization/Settings/DateSettings.cs
    startLine: 6
  assemblies:
  - EvilDICOM
references:
- uid: EvilDICOM.Anonymization.Settings.AnonymizationSettings
  parent: EvilDICOM.Anonymization.Settings
  isExternal: false
  name: AnonymizationSettings
  fullName: EvilDICOM.Anonymization.Settings.AnonymizationSettings
- uid: EvilDICOM.Anonymization.Settings.DateSettings
  parent: EvilDICOM.Anonymization.Settings
  isExternal: false
  name: DateSettings
  fullName: EvilDICOM.Anonymization.Settings.DateSettings
- uid: EvilDICOM.Anonymization.Settings
  isExternal: false
  name: EvilDICOM.Anonymization.Settings
  fullName: EvilDICOM.Anonymization.Settings
